### ISSUE TITLE
Mods that have a version in their name don't get their symlinks updated when they update

### ISSUE THREAD

**Issue by mashedkeyboard** [muttleyxd/arma3-unix-launcher#50]
Take "CUP Vehicles 1.13.0" for example. If the mod were to update, and the name became "CUP Vehicles 1.13.1", then the launcher updates what's listed appropriately, and the generated Arma3.cfg file has the correct path, but the !Workshop folder symlinks don't update with that name.

At present, every time this happens, I have to manually run `arma3-unix-launcher --purge`, rerun Arma 3 manually from Steam, and then reopen the launcher to make this work again. Could this be made easier or automatic on a version change?

**Comment by muttleyxd** [comment]
That's an issue I haven't thought of, I'll try to do something about it this weekend.

**Comment by muttleyxd** [comment]
Fixed with facedb0

Feel free to reopen the issue if the issue persists :)

Note: this causes new symlinks to be created (`@CUP Vehicles 1.13.1` will be created, but `@CUP Vehicles 1.13.0` won't be deleted, I didn't want to introduce logic for cleaning up old links, that's more logic to create bugs and symlinks don't take a lot of space).
